language: c

compiler:
    - clang

before_script:
    - mkdir cmake-build-debug
    - cd cmake-build-debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
    - make
    - chmod a+x ./linked-list-c-test
    - valgrind ./linked-list-c-test

addons:
    apt:
        packages:
            - valgrind

env:
    - VALGRIND_OPTS='--leak-check=full --leak-resolution=med --track-origins=yes --show-leak-kinds=all --vgdb=no'
